apiVersion: apps/v1
kind: Deployment
metadata:
  name: sign-language-deployment
spec:
  replicas: 1
  selector:
    matchLabels:
      app: sign-language
  template:
    metadata:
      labels:
        app: sign-language
    spec:
      containers:
      - name: sign-language-container
        image: image: madhulika0860/sign-language-detection:latest
        ports:
        - containerPort: 5000
---
apiVersion: v1
kind: Service
metadata:
  name: sign-language-service
spec:
  type: LoadBalancer
  selector:
    app: sign-language
  ports:
  - protocol: TCP
    port: 80
    targetPort: 5000
